### ISSUE TITLE
Could not load assembly System.ComponentModel.Annotations

### ISSUE THREAD

**Issue by fbakkes** [SiftScience/sift-dotnet#24]
I added the Sift NuGet package into a .Net 4.6.1 project.
When trying to send the message I received the following error.

Could not load file or assembly 'System.ComponentModel.Annotations, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

Following is the stack trance

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) in f:\dd\ndp\clr\src\BCL\system\threading\Tasks\Task.cs:line 2155
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) in f:\dd\ndp\clr\src\BCL\system\threading\Tasks\Future.cs:line 567
   at System.Threading.Tasks.Task`1.get_Result() in f:\dd\ndp\clr\src\BCL\system\threading\Tasks\Future.cs:line 532

And inner exception

   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext) in f:\dd\ndp\clr\src\BCL\system\runtimehandles.cs:line 1937
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments) in f:\dd\ndp\clr\src\BCL\system\reflection\module.cs:line 850
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg) in f:\dd\ndp\clr\src\BCL\system\reflection\customattribute.cs:line 1885
   at System.Reflection.CustomAttribute.IsCustomAttributeDefined(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Int32 attributeCtorToken, Boolean mustBeInheritable) in f:\dd\ndp\clr\src\BCL\system\reflection\customattribute.cs:line 1620
   at System.Reflection.CustomAttribute.IsDefined(RuntimePropertyInfo property, RuntimeType caType) in f:\dd\ndp\clr\src\BCL\system\reflection\customattribute.cs:line 1265
   at System.Reflection.RuntimePropertyInfo.IsDefined(Type attributeType, Boolean inherit) in f:\dd\ndp\clr\src\BCL\system\reflection\propertyinfo.cs:line 399
   at Newtonsoft.Json.Serialization.DefaultContractResolver.GetSerializableMembers(Type objectType) in /_/Src/Newtonsoft.Json/Serialization/DefaultContractResolver.cs:line 258
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperties(Type type, MemberSerialization memberSerialization) in /_/Src/Newtonsoft.Json/Serialization/DefaultContractResolver.cs:line 1363
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType) in /_/Src/Newtonsoft.Json/Serialization/DefaultContractResolver.cs:line 343
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType) in /_/Src/Newtonsoft.Json/Serialization/DefaultContractResolver.cs:line 1258
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory) in f:\dd\ndp\clr\src\BCL\system\Collections\Concurrent\ConcurrentDictionary.cs:line 1070
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type) in /_/Src/Newtonsoft.Json/Serialization/DefaultContractResolver.cs:line 198
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalWriter.cs:line 71
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType) in /_/Src/Newtonsoft.Json/JsonSerializer.cs:line 1149
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer) in /_/Src/Newtonsoft.Json/JsonConvert.cs:line 665
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value) in /_/Src/Newtonsoft.Json/JsonConvert.cs:line 530
   at Sift.SiftEntity.ToJson()
   at Sift.EventRequest.get_Request()
   at Sift.Client.<SendAsync>d__15`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 184
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 157
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 352
   at Sift.Client.<SendAsync>d__6.MoveNext()

**Comment by viaskal-sift** [comment]
@fbakkes the issue should not be reproducible anymore, could you pls confirm that?

**Comment by viaskal-sift** [comment]
the issue is resolved at the moment
